# Intro to Polars

## Outline

1. Introduction, basic Polars DataFrame API, differences with pandas, simple I/O
2. The expression system, filtering rows, transforming columns
3. Working with semi-structured data, integration with Pydantic
4. Cloud storage, out of core processing with the new streaming engine

## 1. Introduction

### What is Polars?

https://pola.rs/

![Polars](static/polars_github_banner.svg)

> Polars is an open-source library for data manipulation, known for being one of the fastest data processing solutions on a single machine. It features a well-structured, typed API that is both expressive and easy to use.

In summary:

- Expressive API (more familiar to R and Spark users, still approachable to pandas users)
- Fast (thanks to its Rust core)
- Support for zero-copy Apache Arrow data
- Out of core (with its new streaming engine)

### Dataset

We will play with [data from Stack Overflow](https://www.kaggle.com/datasets/stackoverflow/stacksample):

![Stack Overflow data sample](static/stacksample.png)

In [1]:
# Uncomment to generate a sample of the dataset
#
# import polars as pl
#
# pl.scan_csv("data/Questions.csv", encoding="utf8-lossy").collect(engine="streaming").sample(fraction=0.01).write_parquet("data/questions-sample.parquet")
# pl.scan_csv("data/Tags.csv").collect(engine="streaming").write_parquet("data/tags.parquet")

In [2]:
import polars as pl

In [3]:
df = pl.read_parquet("data/questions-sample.parquet")
df.head()

shape: (5, 7)
┌──────────┬─────────────┬─────────────────┬────────────┬───────┬─────────────────┬────────────────┐
│ Id       ┆ OwnerUserId ┆ CreationDate    ┆ ClosedDate ┆ Score ┆ Title           ┆ Body           │
│ ---      ┆ ---         ┆ ---             ┆ ---        ┆ ---   ┆ ---             ┆ ---            │
│ i64      ┆ str         ┆ str             ┆ str        ┆ i64   ┆ str             ┆ str            │
╞══════════╪═════════════╪═════════════════╪════════════╪═══════╪═════════════════╪════════════════╡
│ 8869230  ┆ 1109161     ┆ 2012-01-15T11:1 ┆ NA         ┆ 1     ┆ How to display  ┆ <p>I have a    │
│          ┆             ┆ 1:05Z           ┆            ┆       ┆ two or more     ┆ question about │
│          ┆             ┆                 ┆            ┆       ┆ mar…            ┆ the…           │
│ 31915780 ┆ 4021972     ┆ 2015-08-10T09:1 ┆ NA         ┆ -2    ┆ AngularJS:      ┆ <p>when I get  │
│          ┆             ┆ 5:43Z           ┆            ┆       ┆ $http.get 405   ┆ a request from │
│          ┆             ┆                 ┆            ┆       ┆ (Meth…          ┆ a…             │
│ 30964930 ┆ 2786156     ┆ 2015-06-21T13:1 ┆ NA         ┆ 0     ┆ Invariant       ┆ <p>I'm reading │
│          ┆             ┆ 6:50Z           ┆            ┆       ┆ parameters in   ┆ Bloch's        │
│          ┆             ┆                 ┆            ┆       ┆ Java            ┆ Effecti…       │
│ 38084100 ┆ 2938167     ┆ 2016-06-28T18:5 ┆ NA         ┆ 0     ┆ How to make     ┆ <p>For         │
│          ┆             ┆ 1:24Z           ┆            ┆       ┆ Excel macro     ┆ splitting a    │
│          ┆             ┆                 ┆            ┆       ┆ splitt…         ┆ file into s…   │
│ 9601400  ┆ 346977      ┆ 2012-03-07T12:1 ┆ NA         ┆ 2     ┆ Rails Custom    ┆ <p>I'm trying  │
│          ┆             ┆ 9:37Z           ┆            ┆       ┆ Validators:     ┆ to write up a  │
│          ┆             ┆                 ┆            ┆       ┆ Testi…          ┆ ra…            │
└──────────┴─────────────┴─────────────────┴────────────┴───────┴─────────────────┴────────────────┘

In [4]:
df_tags = pl.read_parquet("data/tags.parquet")
df_tags.head()

shape: (5, 2)
┌─────┬────────────────┐
│ Id  ┆ Tag            │
│ --- ┆ ---            │
│ i64 ┆ str            │
╞═════╪════════════════╡
│ 80  ┆ flex           │
│ 80  ┆ actionscript-3 │
│ 80  ┆ air            │
│ 90  ┆ svn            │
│ 90  ┆ tortoisesvn    │
└─────┴────────────────┘

In [5]:
len(df), len(df_tags)

(12642, 3750994)

In [6]:
!du -h data/{questions*,tags}.parquet

6.0M	data/questions-sample.parquet
 14M	data/tags.parquet

In [7]:
print(f"Estimated size in memory (questions sample): {df_tags.estimated_size() >> 20} MiB")

Estimated size in memory (questions sample): 56 MiB

In [8]:
df.describe()

shape: (9, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ Id         ┆ OwnerUserI ┆ CreationD ┆ ClosedDat ┆ Score     ┆ Title     ┆ Body      │
│ ---        ┆ ---        ┆ d          ┆ ate       ┆ e         ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ f64        ┆ ---        ┆ ---       ┆ ---       ┆ f64       ┆ str       ┆ str       │
│            ┆            ┆ str        ┆ str       ┆ str       ┆           ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 12642.0    ┆ 12642      ┆ 12642     ┆ 12642     ┆ 12642.0   ┆ 12642     ┆ 12642     │
│ null_count ┆ 0.0        ┆ 0          ┆ 0         ┆ 0         ┆ 0.0       ┆ 0         ┆ 0         │
│ mean       ┆ 2.1342e7   ┆ null       ┆ null      ┆ null      ┆ 1.730264  ┆ null      ┆ null      │
│ std        ┆ 1.1516e7   ┆ null       ┆ null      ┆ null      ┆ 10.770727 ┆ null      ┆ null      │
│ min        ┆ 2750.0     ┆ 1000030    ┆ 2008-08-0 ┆ 2010-08-1 ┆ -9.0      ┆ Cached    ┆ <blockquo │
│            ┆            ┆            ┆ 5T19:51:2 ┆ 4T20:49:3 ┆           ┆ hidden    ┆ te>       │
│            ┆            ┆            ┆ 9Z        ┆ 3Z        ┆           ┆ input     ┆ <p><stron │
│            ┆            ┆            ┆           ┆           ┆           ┆ value is  ┆ g>Poss…   │
│            ┆            ┆            ┆           ┆           ┆           ┆ …         ┆           │
│ 25%        ┆ 1.137921e7 ┆ null       ┆ null      ┆ null      ┆ 0.0       ┆ null      ┆ null      │
│ 50%        ┆ 2.187941e7 ┆ null       ┆ null      ┆ null      ┆ 0.0       ┆ null      ┆ null      │
│ 75%        ┆ 3.155418e7 ┆ null       ┆ null      ┆ null      ┆ 1.0       ┆ null      ┆ null      │
│ max        ┆ 4.014e7    ┆ NA         ┆ 2016-10-1 ┆ NA        ┆ 582.0     ┆ zoom      ┆ <ul>      │
│            ┆            ┆            ┆ 9T19:29:0 ┆           ┆           ┆ property, ┆ <li>I     │
│            ┆            ┆            ┆ 6Z        ┆           ┆           ┆ for       ┆ have a    │
│            ┆            ┆            ┆           ┆           ┆           ┆ regular   ┆ task      │
│            ┆            ┆            ┆           ┆           ┆           ┆ vid…      ┆ which c…  │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [9]:
print(df.head(3))

shape: (3, 7)
┌──────────┬─────────────┬─────────────────┬────────────┬───────┬─────────────────┬────────────────┐
│ Id       ┆ OwnerUserId ┆ CreationDate    ┆ ClosedDate ┆ Score ┆ Title           ┆ Body           │
│ ---      ┆ ---         ┆ ---             ┆ ---        ┆ ---   ┆ ---             ┆ ---            │
│ i64      ┆ str         ┆ str             ┆ str        ┆ i64   ┆ str             ┆ str            │
╞══════════╪═════════════╪═════════════════╪════════════╪═══════╪═════════════════╪════════════════╡
│ 8869230  ┆ 1109161     ┆ 2012-01-15T11:1 ┆ NA         ┆ 1     ┆ How to display  ┆ <p>I have a    │
│          ┆             ┆ 1:05Z           ┆            ┆       ┆ two or more     ┆ question about │
│          ┆             ┆                 ┆            ┆       ┆ mar…            ┆ the…           │
│ 31915780 ┆ 4021972     ┆ 2015-08-10T09:1 ┆ NA         ┆ -2    ┆ AngularJS:      ┆ <p>when I get  │
│          ┆             ┆ 5:43Z           ┆            ┆       ┆ $http.get 405   ┆ a request from │
│          ┆             ┆                 ┆            ┆       ┆ (Meth…          ┆ a…             │
│ 30964930 ┆ 2786156     ┆ 2015-06-21T13:1 ┆ NA         ┆ 0     ┆ Invariant       ┆ <p>I'm reading │
│          ┆             ┆ 6:50Z           ┆            ┆       ┆ parameters in   ┆ Bloch's        │
│          ┆             ┆                 ┆            ┆       ┆ Java            ┆ Effecti…       │
└──────────┴─────────────┴─────────────────┴────────────┴───────┴─────────────────┴────────────────┘

In [10]:
type(df["Title"])

polars.series.series.Series

In [11]:
df.dtypes

[Int64, String, String, String, Int64, String, String]

In [12]:
pl.DataFrame({col: dtype for col, dtype in zip(df.columns, df.dtypes)})

shape: (1, 7)
┌────────┬─────────────┬──────────────┬────────────┬────────┬────────┬────────┐
│ Id     ┆ OwnerUserId ┆ CreationDate ┆ ClosedDate ┆ Score  ┆ Title  ┆ Body   │
│ ---    ┆ ---         ┆ ---          ┆ ---        ┆ ---    ┆ ---    ┆ ---    │
│ object ┆ object      ┆ object       ┆ object     ┆ object ┆ object ┆ object │
╞════════╪═════════════╪══════════════╪════════════╪════════╪════════╪════════╡
│ Int64  ┆ String      ┆ String       ┆ String     ┆ Int64  ┆ String ┆ String │
└────────┴─────────────┴──────────────┴────────────┴────────┴────────┴────────┘

In [13]:
df_tags["Tag"].value_counts().sort(by="count", descending=True)

shape: (37_036, 2)
┌───────────────┬────────┐
│ Tag           ┆ count  │
│ ---           ┆ ---    │
│ str           ┆ u32    │
╞═══════════════╪════════╡
│ javascript    ┆ 124155 │
│ java          ┆ 115212 │
│ c#            ┆ 101186 │
│ php           ┆ 98808  │
│ android       ┆ 90659  │
│ …             ┆ …      │
│ drupal-db-api ┆ 1      │
│ instance-eval ┆ 1      │
│ osmarender    ┆ 1      │
│ ipfs          ┆ 1      │
│ ruby-1.9.1    ┆ 1      │
└───────────────┴────────┘

### Differences with pandas

One notable difference with pandas is that Polars DataFrames don't have an index. [This is what the documentation used to say](https://web.archive.org/web/20220206194551/https://pola-rs.github.io/polars-book/user-guide/coming_from_pandas.html#no-index):

> ### No index
>
> They are not needed. Not having them makes things easier. Convince me otherwise

[Since pandas 2.0 it is possible to use PyArrow as backend](https://pandas.pydata.org/docs/whatsnew/v2.0.0.html#argument-dtype-backend-to-return-pyarrow-backed-or-numpy-backed-nullable-dtypes), so the performance gap has become a bit smaller. Still, the considerations about the API and the lazy capabilities stand.

Some advice on how to migrate from pandas can be found at https://docs.pola.rs/user-guide/migration/pandas/

Here comes a trivial I/O microbenchmark (uses the full dataset):

In [14]:
import pandas as pd

In [15]:
%%timeit -n1 -r1
pd.read_csv("data/Questions.csv", encoding_errors="replace").to_csv("/tmp/questions-throwaway.csv")

40.2 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

In [16]:
%%timeit -n1 -r1
pl.read_csv("data/Questions.csv", encoding="utf8-lossy").write_csv("/tmp/questions-throwaway.csv")

3.22 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

Pro tip: You can convert your Polars `DataFrame` to pandas at any time!

In [17]:
df.to_pandas()

,Id,OwnerUserId,CreationDate,ClosedDate,Score,Title,Body
0,8869230,1109161,2012-01-15T11:11:05Z,NA,1,How to display two or more markers on the same...,<p>I have a question about the GOOGLE MAP API....
1,31915780,4021972,2015-08-10T09:15:43Z,NA,-2,AngularJS: $http.get 405 (Method Not Allowed),"<p>when I get a request from a url,like this:<..."
2,30964930,2786156,2015-06-21T13:16:50Z,NA,0,Invariant parameters in Java,<p>I'm reading Bloch's Effective Java and now ...
3,38084100,2938167,2016-06-28T18:51:24Z,NA,0,How to make Excel macro splitting file into se...,<p>For splitting a file into several files by ...
4,9601400,346977,2012-03-07T12:19:37Z,NA,2,Rails Custom Validators: Testing options,<p>I'm trying to write up a rails gem that inv...
...,...,...,...,...,...,...,...
12637,31228310,5081947,2015-07-05T08:02:22Z,NA,-2,java Scanner input issues,<p>Im writing an assignment where i need to se...
12638,29523070,937013,2015-04-08T18:55:47Z,NA,-1,Encoding list variable to flag variable,<p>I've got <code>pandas.DataFrame</code>:</p>...
12639,17575130,2457351,2013-07-10T15:44:16Z,NA,1,Get Value from BoundField,<p>I have a form that I'm using to create a ur...
12640,22788040,969345,2014-04-01T13:54:45Z,NA,1,how to change color of popup window in eclipse,"<p>In image\n [1]: <a href=""http://i.stack.im..."
12641,31369080,5108124,2015-07-12T14:50:42Z,NA,0,TCP-Socket verify SSL-certificate for SslStrea...,<p>I am currently working on a project which c...

## 2. The expression system, filtering rows, transforming columns

The essential building blocks in Polars are expressions: functions that receive a Series and transform it into another Series. Expressions [start with a root](https://stackoverflow.com/a/72121352/554319), and then you can chain more operations:

In [18]:
pl.col("OwnerUserId")

In [19]:
op = pl.col("Title").str.starts_with("W")
op

Expressions are completely decoupled from the data and can be manipulated independently!

To apply them, you can use some of the [contexts](https://docs.pola.rs/user-guide/concepts/expressions-and-contexts/#contexts):

In [20]:
df.head(1)

shape: (1, 7)
┌─────────┬─────────────┬─────────────────┬────────────┬───────┬─────────────────┬─────────────────┐
│ Id      ┆ OwnerUserId ┆ CreationDate    ┆ ClosedDate ┆ Score ┆ Title           ┆ Body            │
│ ---     ┆ ---         ┆ ---             ┆ ---        ┆ ---   ┆ ---             ┆ ---             │
│ i64     ┆ str         ┆ str             ┆ str        ┆ i64   ┆ str             ┆ str             │
╞═════════╪═════════════╪═════════════════╪════════════╪═══════╪═════════════════╪═════════════════╡
│ 8869230 ┆ 1109161     ┆ 2012-01-15T11:1 ┆ NA         ┆ 1     ┆ How to display  ┆ <p>I have a     │
│         ┆             ┆ 1:05Z           ┆            ┆       ┆ two or more     ┆ question about  │
│         ┆             ┆                 ┆            ┆       ┆ mar…            ┆ the…            │
└─────────┴─────────────┴─────────────────┴────────────┴───────┴─────────────────┴─────────────────┘

In [21]:
df.select(
    pl.col("OwnerUserId").n_unique(),
    pl.col("CreationDate").str.to_datetime("%Y-%m-%dT%H:%M:%SZ").dt.hour().mean().alias("mean_hour"),
    pl.col("Score").min().alias("min_score"),
    pl.col("Score").max().alias("max_score"),
    pl.col("Title").str.len_chars().max(),
)

shape: (1, 5)
┌─────────────┬───────────┬───────────┬───────────┬───────┐
│ OwnerUserId ┆ mean_hour ┆ min_score ┆ max_score ┆ Title │
│ ---         ┆ ---       ┆ ---       ┆ ---       ┆ ---   │
│ u32         ┆ f64       ┆ i64       ┆ i64       ┆ u32   │
╞═════════════╪═══════════╪═══════════╪═══════════╪═══════╡
│ 12200       ┆ 12.529347 ┆ -9        ┆ 582       ┆ 156   │
└─────────────┴───────────┴───────────┴───────────┴───────┘

By passing more column names, you can apply the same operation to different columns:

In [22]:
df.select(
    pl.col("Title", "Body").str.to_lowercase(),
).head(3)

shape: (3, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ Title                           ┆ Body                            │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ how to display two or more mar… ┆ <p>i have a question about the… │
│ angularjs: $http.get 405 (meth… ┆ <p>when i get a request from a… │
│ invariant parameters in java    ┆ <p>i'm reading bloch's effecti… │
└─────────────────────────────────┴─────────────────────────────────┘

In [23]:
df.select(pl.all().exclude("Body", "Title"))

shape: (12_642, 5)
┌──────────┬─────────────┬──────────────────────┬────────────┬───────┐
│ Id       ┆ OwnerUserId ┆ CreationDate         ┆ ClosedDate ┆ Score │
│ ---      ┆ ---         ┆ ---                  ┆ ---        ┆ ---   │
│ i64      ┆ str         ┆ str                  ┆ str        ┆ i64   │
╞══════════╪═════════════╪══════════════════════╪════════════╪═══════╡
│ 8869230  ┆ 1109161     ┆ 2012-01-15T11:11:05Z ┆ NA         ┆ 1     │
│ 31915780 ┆ 4021972     ┆ 2015-08-10T09:15:43Z ┆ NA         ┆ -2    │
│ 30964930 ┆ 2786156     ┆ 2015-06-21T13:16:50Z ┆ NA         ┆ 0     │
│ 38084100 ┆ 2938167     ┆ 2016-06-28T18:51:24Z ┆ NA         ┆ 0     │
│ 9601400  ┆ 346977      ┆ 2012-03-07T12:19:37Z ┆ NA         ┆ 2     │
│ …        ┆ …           ┆ …                    ┆ …          ┆ …     │
│ 31228310 ┆ 5081947     ┆ 2015-07-05T08:02:22Z ┆ NA         ┆ -2    │
│ 29523070 ┆ 937013      ┆ 2015-04-08T18:55:47Z ┆ NA         ┆ -1    │
│ 17575130 ┆ 2457351     ┆ 2013-07-10T15:44:16Z ┆ NA         ┆ 1     │
│ 22788040 ┆ 969345      ┆ 2014-04-01T13:54:45Z ┆ NA         ┆ 1     │
│ 31369080 ┆ 5108124     ┆ 2015-07-12T14:50:42Z ┆ NA         ┆ 0     │
└──────────┴─────────────┴──────────────────────┴────────────┴───────┘

And there are even complex column selectors:

In [24]:
import polars.selectors as cs

In [25]:
df.select(cs.contains("Id").exclude("Id")).head(3)

shape: (3, 1)
┌─────────────┐
│ OwnerUserId │
│ ---         │
│ str         │
╞═════════════╡
│ 1109161     │
│ 4021972     │
│ 2786156     │
└─────────────┘

In [26]:
df.select(
    cs.contains("Id").cast(pl.Utf8).n_unique()
)

shape: (1, 2)
┌───────┬─────────────┐
│ Id    ┆ OwnerUserId │
│ ---   ┆ ---         │
│ u32   ┆ u32         │
╞═══════╪═════════════╡
│ 12642 ┆ 12200       │
└───────┴─────────────┘

Apart from `.select`, you can also use `.with_columns`:

In [27]:
df.with_columns(
    pl.col("Title").str.to_lowercase()#.alias("title_lower"),
)

shape: (12_642, 7)
┌──────────┬─────────────┬─────────────────┬────────────┬───────┬─────────────────┬────────────────┐
│ Id       ┆ OwnerUserId ┆ CreationDate    ┆ ClosedDate ┆ Score ┆ Title           ┆ Body           │
│ ---      ┆ ---         ┆ ---             ┆ ---        ┆ ---   ┆ ---             ┆ ---            │
│ i64      ┆ str         ┆ str             ┆ str        ┆ i64   ┆ str             ┆ str            │
╞══════════╪═════════════╪═════════════════╪════════════╪═══════╪═════════════════╪════════════════╡
│ 8869230  ┆ 1109161     ┆ 2012-01-15T11:1 ┆ NA         ┆ 1     ┆ how to display  ┆ <p>I have a    │
│          ┆             ┆ 1:05Z           ┆            ┆       ┆ two or more     ┆ question about │
│          ┆             ┆                 ┆            ┆       ┆ mar…            ┆ the…           │
│ 31915780 ┆ 4021972     ┆ 2015-08-10T09:1 ┆ NA         ┆ -2    ┆ angularjs:      ┆ <p>when I get  │
│          ┆             ┆ 5:43Z           ┆            ┆       ┆ $http.get 405   ┆ a request from │
│          ┆             ┆                 ┆            ┆       ┆ (meth…          ┆ a…             │
│ 30964930 ┆ 2786156     ┆ 2015-06-21T13:1 ┆ NA         ┆ 0     ┆ invariant       ┆ <p>I'm reading │
│          ┆             ┆ 6:50Z           ┆            ┆       ┆ parameters in   ┆ Bloch's        │
│          ┆             ┆                 ┆            ┆       ┆ java            ┆ Effecti…       │
│ 38084100 ┆ 2938167     ┆ 2016-06-28T18:5 ┆ NA         ┆ 0     ┆ how to make     ┆ <p>For         │
│          ┆             ┆ 1:24Z           ┆            ┆       ┆ excel macro     ┆ splitting a    │
│          ┆             ┆                 ┆            ┆       ┆ splitt…         ┆ file into s…   │
│ 9601400  ┆ 346977      ┆ 2012-03-07T12:1 ┆ NA         ┆ 2     ┆ rails custom    ┆ <p>I'm trying  │
│          ┆             ┆ 9:37Z           ┆            ┆       ┆ validators:     ┆ to write up a  │
│          ┆             ┆                 ┆            ┆       ┆ testi…          ┆ ra…            │
│ …        ┆ …           ┆ …               ┆ …          ┆ …     ┆ …               ┆ …              │
│ 31228310 ┆ 5081947     ┆ 2015-07-05T08:0 ┆ NA         ┆ -2    ┆ java scanner    ┆ <p>Im writing  │
│          ┆             ┆ 2:22Z           ┆            ┆       ┆ input issues    ┆ an assignment  │
│          ┆             ┆                 ┆            ┆       ┆                 ┆ wh…            │
│ 29523070 ┆ 937013      ┆ 2015-04-08T18:5 ┆ NA         ┆ -1    ┆ encoding list   ┆ <p>I've got    │
│          ┆             ┆ 5:47Z           ┆            ┆       ┆ variable to     ┆ <code>pandas.D │
│          ┆             ┆                 ┆            ┆       ┆ flag…           ┆ ataF…          │
│ 17575130 ┆ 2457351     ┆ 2013-07-10T15:4 ┆ NA         ┆ 1     ┆ get value from  ┆ <p>I have a    │
│          ┆             ┆ 4:16Z           ┆            ┆       ┆ boundfield      ┆ form that I'm  │
│          ┆             ┆                 ┆            ┆       ┆                 ┆ usin…          │
│ 22788040 ┆ 969345      ┆ 2014-04-01T13:5 ┆ NA         ┆ 1     ┆ how to change   ┆ <p>In image    │
│          ┆             ┆ 4:45Z           ┆            ┆       ┆ color of popup  ┆ [1]: <a        │
│          ┆             ┆                 ┆            ┆       ┆ w…              ┆ href="ht…      │
│ 31369080 ┆ 5108124     ┆ 2015-07-12T14:5 ┆ NA         ┆ 0     ┆ tcp-socket      ┆ <p>I am        │
│          ┆             ┆ 0:42Z           ┆            ┆       ┆ verify          ┆ currently      │
│          ┆             ┆                 ┆            ┆       ┆ ssl-certific…   ┆ working on a…  │
└──────────┴─────────────┴─────────────────┴────────────┴───────┴─────────────────┴────────────────┘

And finally, you can use expressions to filter rows as well using `.filter`:

In [28]:
df.filter(
    (pl.col("ClosedDate") != "NA") & (pl.col("Score") < 0)
)

shape: (163, 7)
┌──────────┬─────────────┬────────────────┬────────────────┬───────┬───────────────┬───────────────┐
│ Id       ┆ OwnerUserId ┆ CreationDate   ┆ ClosedDate     ┆ Score ┆ Title         ┆ Body          │
│ ---      ┆ ---         ┆ ---            ┆ ---            ┆ ---   ┆ ---           ┆ ---           │
│ i64      ┆ str         ┆ str            ┆ str            ┆ i64   ┆ str           ┆ str           │
╞══════════╪═════════════╪════════════════╪════════════════╪═══════╪═══════════════╪═══════════════╡
│ 34357630 ┆ 5544537     ┆ 2015-12-18T14: ┆ 2015-12-21T20: ┆ -2    ┆ MergeSort     ┆ <p>I've to    │
│          ┆             ┆ 16:23Z         ┆ 49:24Z         ┆       ┆ without       ┆ remove the    │
│          ┆             ┆                ┆                ┆       ┆ second recur… ┆ second c…     │
│ 36243930 ┆ 4056924     ┆ 2016-03-27T04: ┆ 2016-03-27T08: ┆ -2    ┆ Download      ┆ <p>I'am       │
│          ┆             ┆ 45:46Z         ┆ 00:43Z         ┆       ┆ image from    ┆ developing an │
│          ┆             ┆                ┆                ┆       ┆ server and…   ┆ android …     │
│ 37579290 ┆ 6122009     ┆ 2016-06-01T21: ┆ 2016-06-01T21: ┆ -2    ┆ Line          ┆ <p>Can        │
│          ┆             ┆ 42:43Z         ┆ 46:08Z         ┆       ┆ Terminator    ┆ someone       │
│          ┆             ┆                ┆                ┆       ┆ (JavaScript)  ┆ please        │
│          ┆             ┆                ┆                ┆       ┆               ┆ explain …     │
│ 39361680 ┆ 4628328     ┆ 2016-09-07T05: ┆ 2016-09-07T05: ┆ -4    ┆ some issue    ┆ <p>i'm        │
│          ┆             ┆ 17:19Z         ┆ 27:27Z         ┆       ┆ with string   ┆ reading the C │
│          ┆             ┆                ┆                ┆       ┆ in C          ┆ programmi…    │
│ 26500640 ┆ 4168505     ┆ 2014-10-22T05: ┆ 2014-10-22T09: ┆ -1    ┆ How to choose ┆ <p>I am       │
│          ┆             ┆ 07:09Z         ┆ 30:55Z         ┆       ┆ between two   ┆ trying to     │
│          ┆             ┆                ┆                ┆       ┆ item…         ┆ figure out h… │
│ …        ┆ …           ┆ …              ┆ …              ┆ …     ┆ …             ┆ …             │
│ 24655730 ┆ 3820752     ┆ 2014-07-09T13: ┆ 2014-07-09T17: ┆ -1    ┆ Error         ┆ <p>I coded a  │
│          ┆             ┆ 59:16Z         ┆ 20:35Z         ┆       ┆ encountered   ┆ query on      │
│          ┆             ┆                ┆                ┆       ┆ when using O… ┆ entity l…     │
│ 30045000 ┆ 2978895     ┆ 2015-05-05T05: ┆ 2015-05-05T06: ┆ -1    ┆ How to pass   ┆ <p>Iam        │
│          ┆             ┆ 35:27Z         ┆ 55:22Z         ┆       ┆ multiple      ┆ writing my    │
│          ┆             ┆                ┆                ┆       ┆ search pa…    ┆ code in php … │
│ 12676600 ┆ 1711600     ┆ 2012-10-01T15: ┆ 2012-10-02T09: ┆ -5    ┆ C printf      ┆ <p>In C       │
│          ┆             ┆ 46:38Z         ┆ 03:10Z         ┆       ┆ format        ┆ language, out │
│          ┆             ┆                ┆                ┆       ┆ strings       ┆ of the f…     │
│ 18122100 ┆ 1899840     ┆ 2013-08-08T09: ┆ 2013-08-30T09: ┆ -1    ┆ Why Settings  ┆ <p>I have a   │
│          ┆             ┆ 10:39Z         ┆ 30:17Z         ┆       ┆ app doesnot   ┆ created an    │
│          ┆             ┆                ┆                ┆       ┆ list …        ┆ app, co…      │
│ 28642170 ┆ 1879973     ┆ 2015-02-21T04: ┆ 2015-02-21T10: ┆ -3    ┆ How to split  ┆ <p>I'm having │
│          ┆             ┆ 43:28Z         ┆ 38:29Z         ┆       ┆ spacing and | ┆ trouble       │
│          ┆             ┆                ┆                ┆       ┆ in …          ┆ splittin…     │
└──────────┴─────────────┴────────────────┴────────────────┴───────┴───────────────┴───────────────┘

What users have made the most number of questions?

In [29]:
df.head(1)

shape: (1, 7)
┌─────────┬─────────────┬─────────────────┬────────────┬───────┬─────────────────┬─────────────────┐
│ Id      ┆ OwnerUserId ┆ CreationDate    ┆ ClosedDate ┆ Score ┆ Title           ┆ Body            │
│ ---     ┆ ---         ┆ ---             ┆ ---        ┆ ---   ┆ ---             ┆ ---             │
│ i64     ┆ str         ┆ str             ┆ str        ┆ i64   ┆ str             ┆ str             │
╞═════════╪═════════════╪═════════════════╪════════════╪═══════╪═════════════════╪═════════════════╡
│ 8869230 ┆ 1109161     ┆ 2012-01-15T11:1 ┆ NA         ┆ 1     ┆ How to display  ┆ <p>I have a     │
│         ┆             ┆ 1:05Z           ┆            ┆       ┆ two or more     ┆ question about  │
│         ┆             ┆                 ┆            ┆       ┆ mar…            ┆ the…            │
└─────────┴─────────────┴─────────────────┴────────────┴───────┴─────────────────┴─────────────────┘

In [30]:
df.group_by("OwnerUserId").agg(
    pl.len(),
    pl.col("CreationDate").min(),
    (pl.col("Score") < 0).sum().alias("negative_score"),
).sort("len", descending=True).head(10)

shape: (10, 4)
┌─────────────┬─────┬──────────────────────┬────────────────┐
│ OwnerUserId ┆ len ┆ CreationDate         ┆ negative_score │
│ ---         ┆ --- ┆ ---                  ┆ ---            │
│ str         ┆ u32 ┆ str                  ┆ u32            │
╞═════════════╪═════╪══════════════════════╪════════════════╡
│ NA          ┆ 145 ┆ 2008-10-01T10:29:49Z ┆ 3              │
│ 340688      ┆ 4   ┆ 2012-04-17T20:27:06Z ┆ 0              │
│ 470184      ┆ 3   ┆ 2014-05-09T14:51:41Z ┆ 0              │
│ 996431      ┆ 3   ┆ 2012-01-13T22:02:41Z ┆ 0              │
│ 2648        ┆ 3   ┆ 2009-11-02T21:57:43Z ┆ 0              │
│ 1668069     ┆ 3   ┆ 2014-01-29T15:59:07Z ┆ 0              │
│ 2576903     ┆ 3   ┆ 2013-10-26T08:05:03Z ┆ 0              │
│ 13009       ┆ 3   ┆ 2009-06-19T22:28:46Z ┆ 0              │
│ 651174      ┆ 3   ┆ 2012-02-22T03:12:27Z ┆ 0              │
│ 280244      ┆ 3   ┆ 2010-12-08T12:01:49Z ┆ 0              │
└─────────────┴─────┴──────────────────────┴────────────────┘

### Exercise

What are the most upvoted Python questions?

In [31]:
df.join(df_tags, on="Id", how="left")

shape: (37_603, 8)
┌──────────┬─────────────┬─────────────┬────────────┬───────┬────────────┬────────────┬────────────┐
│ Id       ┆ OwnerUserId ┆ CreationDat ┆ ClosedDate ┆ Score ┆ Title      ┆ Body       ┆ Tag        │
│ ---      ┆ ---         ┆ e           ┆ ---        ┆ ---   ┆ ---        ┆ ---        ┆ ---        │
│ i64      ┆ str         ┆ ---         ┆ str        ┆ i64   ┆ str        ┆ str        ┆ str        │
│          ┆             ┆ str         ┆            ┆       ┆            ┆            ┆            │
╞══════════╪═════════════╪═════════════╪════════════╪═══════╪════════════╪════════════╪════════════╡
│ 8869230  ┆ 1109161     ┆ 2012-01-15T ┆ NA         ┆ 1     ┆ How to     ┆ <p>I have  ┆ google-map │
│          ┆             ┆ 11:11:05Z   ┆            ┆       ┆ display    ┆ a question ┆ s          │
│          ┆             ┆             ┆            ┆       ┆ two or     ┆ about the… ┆            │
│          ┆             ┆             ┆            ┆       ┆ more mar…  ┆            ┆            │
│ 8869230  ┆ 1109161     ┆ 2012-01-15T ┆ NA         ┆ 1     ┆ How to     ┆ <p>I have  ┆ google-map │
│          ┆             ┆ 11:11:05Z   ┆            ┆       ┆ display    ┆ a question ┆ s-api-3    │
│          ┆             ┆             ┆            ┆       ┆ two or     ┆ about the… ┆            │
│          ┆             ┆             ┆            ┆       ┆ more mar…  ┆            ┆            │
│ 31915780 ┆ 4021972     ┆ 2015-08-10T ┆ NA         ┆ -2    ┆ AngularJS: ┆ <p>when I  ┆ angularjs  │
│          ┆             ┆ 09:15:43Z   ┆            ┆       ┆ $http.get  ┆ get a      ┆            │
│          ┆             ┆             ┆            ┆       ┆ 405 (Meth… ┆ request    ┆            │
│          ┆             ┆             ┆            ┆       ┆            ┆ from a…    ┆            │
│ 31915780 ┆ 4021972     ┆ 2015-08-10T ┆ NA         ┆ -2    ┆ AngularJS: ┆ <p>when I  ┆ http       │
│          ┆             ┆ 09:15:43Z   ┆            ┆       ┆ $http.get  ┆ get a      ┆            │
│          ┆             ┆             ┆            ┆       ┆ 405 (Meth… ┆ request    ┆            │
│          ┆             ┆             ┆            ┆       ┆            ┆ from a…    ┆            │
│ 31915780 ┆ 4021972     ┆ 2015-08-10T ┆ NA         ┆ -2    ┆ AngularJS: ┆ <p>when I  ┆ http-statu │
│          ┆             ┆ 09:15:43Z   ┆            ┆       ┆ $http.get  ┆ get a      ┆ s-code-405 │
│          ┆             ┆             ┆            ┆       ┆ 405 (Meth… ┆ request    ┆            │
│          ┆             ┆             ┆            ┆       ┆            ┆ from a…    ┆            │
│ …        ┆ …           ┆ …           ┆ …          ┆ …     ┆ …          ┆ …          ┆ …          │
│ 22788040 ┆ 969345      ┆ 2014-04-01T ┆ NA         ┆ 1     ┆ how to     ┆ <p>In      ┆ eclipse    │
│          ┆             ┆ 13:54:45Z   ┆            ┆       ┆ change     ┆ image      ┆            │
│          ┆             ┆             ┆            ┆       ┆ color of   ┆ [1]: <a    ┆            │
│          ┆             ┆             ┆            ┆       ┆ popup w…   ┆ href="ht…  ┆            │
│ 31369080 ┆ 5108124     ┆ 2015-07-12T ┆ NA         ┆ 0     ┆ TCP-Socket ┆ <p>I am    ┆ c#         │
│          ┆             ┆ 14:50:42Z   ┆            ┆       ┆ verify SSL ┆ currently  ┆            │
│          ┆             ┆             ┆            ┆       ┆ -certific… ┆ working on ┆            │
│          ┆             ┆             ┆            ┆       ┆            ┆ a…         ┆            │
│ 31369080 ┆ 5108124     ┆ 2015-07-12T ┆ NA         ┆ 0     ┆ TCP-Socket ┆ <p>I am    ┆ sockets    │
│          ┆             ┆ 14:50:42Z   ┆            ┆       ┆ verify SSL ┆ currently  ┆            │
│          ┆             ┆             ┆            ┆       ┆ -certific… ┆ working on ┆            │
│          ┆             ┆             ┆            ┆       ┆            ┆ a…         ┆            │
│ 31369080 ┆ 5108124     ┆ 2015-07-12T ┆ NA         ┆ 0     ┆ TCP-Socket ┆ <p>I am    ┆ ssl        │
│          ┆             ┆ 14:50:42Z   ┆            ┆       ┆ verify SSL ┆ currently  ┆            │
│          ┆             ┆             ┆            ┆       ┆ -certific… ┆ working on ┆            │
│          ┆             ┆             ┆            ┆       ┆            ┆ a…         ┆            │
│ 31369080 ┆ 5108124     ┆ 2015-07-12T ┆ NA         ┆ 0     ┆ TCP-Socket ┆ <p>I am    ┆ tcp        │
│          ┆             ┆ 14:50:42Z   ┆            ┆       ┆ verify SSL ┆ currently  ┆            │
│          ┆             ┆             ┆            ┆       ┆ -certific… ┆ working on ┆            │
│          ┆             ┆             ┆            ┆       ┆            ┆ a…         ┆            │
└──────────┴─────────────┴─────────────┴────────────┴───────┴────────────┴────────────┴────────────┘

In [32]:
(
    df.join(
        (
            df_tags
            .filter(pl.col("Tag").str.to_lowercase().str.contains("python"))
            .unique(subset=["Id"])
        ),
        on="Id",
        how="inner",
    ).sort("Score", descending=True)
)

shape: (682, 8)
┌──────────┬─────────────┬──────────────┬─────────────┬───────┬─────────────┬─────────────┬────────┐
│ Id       ┆ OwnerUserId ┆ CreationDate ┆ ClosedDate  ┆ Score ┆ Title       ┆ Body        ┆ Tag    │
│ ---      ┆ ---         ┆ ---          ┆ ---         ┆ ---   ┆ ---         ┆ ---         ┆ ---    │
│ i64      ┆ str         ┆ str          ┆ str         ┆ i64   ┆ str         ┆ str         ┆ str    │
╞══════════╪═════════════╪══════════════╪═════════════╪═══════╪═════════════╪═════════════╪════════╡
│ 265960   ┆ 1512        ┆ 2008-11-05T1 ┆ NA          ┆ 282   ┆ Best way to ┆ <p>It seems ┆ python │
│          ┆             ┆ 7:30:32Z     ┆             ┆       ┆ strip       ┆ like there  ┆        │
│          ┆             ┆              ┆             ┆       ┆ punctuation ┆ should …    ┆        │
│          ┆             ┆              ┆             ┆       ┆ …           ┆             ┆        │
│ 1796180  ┆ 49697       ┆ 2009-11-25T1 ┆ NA          ┆ 170   ┆ How can I   ┆ <p>I've     ┆ python │
│          ┆             ┆ 0:59:46Z     ┆             ┆       ┆ get a list  ┆ seen plenty ┆        │
│          ┆             ┆              ┆             ┆       ┆ of all cl…  ┆ of example… ┆        │
│ 4055860  ┆ 184077      ┆ 2010-10-29T2 ┆ NA          ┆ 69    ┆ Unit        ┆ <p>I am     ┆ python │
│          ┆             ┆ 0:57:31Z     ┆             ┆       ┆ testing     ┆ trying to   ┆        │
│          ┆             ┆              ┆             ┆       ┆ with django ┆ come up     ┆        │
│          ┆             ┆              ┆             ┆       ┆ -celer…     ┆ with…       ┆        │
│ 707380   ┆ 20712       ┆ 2009-04-01T2 ┆ NA          ┆ 61    ┆ In Python   ┆ <p>If I     ┆ python │
│          ┆             ┆ 1:23:39Z     ┆             ┆       ┆ how can I   ┆ have the    ┆        │
│          ┆             ┆              ┆             ┆       ┆ access "st… ┆ following   ┆        │
│          ┆             ┆              ┆             ┆       ┆             ┆ pyt…        ┆        │
│ 19859840 ┆ 354633      ┆ 2013-11-08T1 ┆ NA          ┆ 47    ┆ Excluding   ┆ <p>I'm      ┆ python │
│          ┆             ┆ 3:06:31Z     ┆             ┆       ┆ directories ┆ writing a   ┆        │
│          ┆             ┆              ┆             ┆       ┆ in os.wa…   ┆ script that ┆        │
│          ┆             ┆              ┆             ┆       ┆             ┆ d…          ┆        │
│ …        ┆ …           ┆ …            ┆ …           ┆ …     ┆ …           ┆ …           ┆ …      │
│ 33710870 ┆ 5562307     ┆ 2015-11-14T1 ┆ NA          ┆ -4    ┆ Indentation ┆ <p>The code ┆ python │
│          ┆             ┆ 6:51:58Z     ┆             ┆       ┆ Error       ┆ is set run  ┆        │
│          ┆             ┆              ┆             ┆       ┆ expected an ┆ a comma…    ┆        │
│          ┆             ┆              ┆             ┆       ┆ i…          ┆             ┆        │
│ 24829860 ┆ 3853767     ┆ 2014-07-18T1 ┆ NA          ┆ -4    ┆ Calculating ┆ <p>I have a ┆ python │
│          ┆             ┆ 6:31:53Z     ┆             ┆       ┆ percentile  ┆ DataFrame   ┆        │
│          ┆             ┆              ┆             ┆       ┆ ranks o…    ┆ df. This…   ┆        │
│ 33316330 ┆ 5473576     ┆ 2015-10-24T0 ┆ 2015-11-01T ┆ -5    ┆ How to blit ┆ <p>I wanted ┆ python │
│          ┆             ┆ 8:56:42Z     ┆ 17:35:16Z   ┆       ┆ a random    ┆ to choose   ┆        │
│          ┆             ┆              ┆             ┆       ┆ image fro…  ┆ an image…   ┆        │
│ 25021120 ┆ 718762      ┆ 2014-07-29T1 ┆ NA          ┆ -5    ┆ Equal sign  ┆ <p>Please   ┆ python │
│          ┆             ┆ 7:09:25Z     ┆             ┆       ┆ in a for    ┆ explain     ┆        │
│          ┆             ┆              ┆             ┆       ┆ loop itera… ┆ what is     ┆        │
│          ┆             ┆              ┆             ┆       ┆             ┆ happ…       ┆        │
│ 32330570 ┆ 5160619     ┆ 2015-09-01T1 ┆ NA          ┆ -5    ┆ Parsing a   ┆ <p>I'm      ┆ python │
│          ┆             ┆ 1:34:33Z     ┆             ┆       ┆ long string ┆ trying to   ┆        │
│          ┆             ┆              ┆             ┆       ┆ in pytho…   ┆ parse a     ┆        │
│          ┆             ┆              ┆             ┆       ┆             ┆ long …      ┆        │
└──────────┴─────────────┴──────────────┴─────────────┴───────┴─────────────┴─────────────┴────────┘

## 3. Working with semi-structured data, integration with Pydantic

In Polars, working with columns that contain lists or even dictionaries is straightforward:

In [33]:
df_tags_c = df_tags.group_by("Id").agg(pl.col("Tag"))
df_tags_c.head(3)

shape: (3, 2)
┌──────────┬─────────────────────────────────┐
│ Id       ┆ Tag                             │
│ ---      ┆ ---                             │
│ i64      ┆ list[str]                       │
╞══════════╪═════════════════════════════════╡
│ 32590950 ┆ ["php", "ajax", "sweetalert"]   │
│ 30328510 ┆ ["ajax", "html5", … "restful-a… │
│ 31826630 ┆ ["data-structures"]             │
└──────────┴─────────────────────────────────┘

In [34]:
df_tags_c.group_by("Id").agg(
    pl.col("Tag").list.len().get(0).alias("tag_count"),
).sort("tag_count", descending=True).head(10)

shape: (10, 2)
┌──────────┬───────────┐
│ Id       ┆ tag_count │
│ ---      ┆ ---       │
│ i64      ┆ u32       │
╞══════════╪═══════════╡
│ 29445810 ┆ 5         │
│ 31208200 ┆ 5         │
│ 33956000 ┆ 5         │
│ 32193250 ┆ 5         │
│ 10090950 ┆ 5         │
│ 11248790 ┆ 5         │
│ 24352030 ┆ 5         │
│ 21863230 ┆ 5         │
│ 20472230 ┆ 5         │
│ 1795280  ┆ 5         │
└──────────┴───────────┘

In [35]:
df_tags_c.select(
    pl.all(),
    pl.col("Tag").list.eval(
        pl.all().str.to_uppercase(),
    ).alias("tags_upper"),
).head()

shape: (5, 3)
┌──────────┬─────────────────────────────────┬─────────────────────────────────┐
│ Id       ┆ Tag                             ┆ tags_upper                      │
│ ---      ┆ ---                             ┆ ---                             │
│ i64      ┆ list[str]                       ┆ list[str]                       │
╞══════════╪═════════════════════════════════╪═════════════════════════════════╡
│ 32590950 ┆ ["php", "ajax", "sweetalert"]   ┆ ["PHP", "AJAX", "SWEETALERT"]   │
│ 30328510 ┆ ["ajax", "html5", … "restful-a… ┆ ["AJAX", "HTML5", … "RESTFUL-A… │
│ 31826630 ┆ ["data-structures"]             ┆ ["DATA-STRUCTURES"]             │
│ 29417240 ┆ ["java", "spring", … "servlets… ┆ ["JAVA", "SPRING", … "SERVLETS… │
│ 17582830 ┆ ["python", "module", "beautifu… ┆ ["PYTHON", "MODULE", "BEAUTIFU… │
└──────────┴─────────────────────────────────┴─────────────────────────────────┘

In [36]:
df_tags.group_by("Id").agg(pl.col("Tag"))

shape: (1_264_216, 2)
┌──────────┬─────────────────────────────────┐
│ Id       ┆ Tag                             │
│ ---      ┆ ---                             │
│ i64      ┆ list[str]                       │
╞══════════╪═════════════════════════════════╡
│ 17557770 ┆ ["java", "box2d", "libgdx"]     │
│ 16054440 ┆ ["python", "django", "django-s… │
│ 9265780  ┆ ["gwt", "web-deployment"]       │
│ 39771760 ┆ ["php", "xml", … "ascii"]       │
│ 22513660 ┆ ["java", "weblogic11g"]         │
│ …        ┆ …                               │
│ 3830380  ┆ ["sql"]                         │
│ 23640780 ┆ ["javascript", "regex"]         │
│ 38852740 ┆ ["pagination", "shopify", … "l… │
│ 14010580 ┆ ["objective-c"]                 │
│ 9337720  ┆ ["ios", "video", "avassetreade… │
└──────────┴─────────────────────────────────┘

Semi-structured data might come from JSON APIs. You can leverage the Polars and Pydantic integration:

In [37]:
import typing as t
import datetime as dt

import httpx
from pydantic import BaseModel, TypeAdapter, Field

In [38]:
resp = httpx.get("https://api.tfl.gov.uk/Line/dlr/Arrivals/940GZZDLSOQ")
resp.json()

[{'$type': 'Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities',
  'id': '-1249460012',
  'operationType': 1,
  'vehicleId': '',
  'naptanId': '940GZZDLSOQ',
  'stationName': 'South Quay DLR Station',
  'lineId': 'dlr',
  'lineName': 'DLR',
  'platformName': 'Platform 2',
  'direction': 'inbound',
  'bearing': '',
  'destinationNaptanId': '940GZZDLBNK',
  'destinationName': 'Bank DLR Station',
  'timestamp': '2025-04-08T09:41:20.3911746Z',
  'timeToStation': 288,
  'currentLocation': '',
  'towards': '',
  'expectedArrival': '2025-04-08T09:46:08Z',
  'timeToLive': '2025-04-08T09:46:08Z',
  'modeName': 'dlr',
  'timing': {'$type': 'Tfl.Api.Presentation.Entities.PredictionTiming, Tfl.Api.Presentation.Entities',
   'countdownServerAdjustment': '00:00:00',
   'source': '0001-01-01T00:00:00',
   'insert': '0001-01-01T00:00:00',
   'read': '2025-04-08T09:41:08.296Z',
   'sent': '2025-04-08T09:41:20Z',
   'received': '0001-01-01T00:00:00'}},
 {'$type': 'Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities',
  'id': '-1249460012',
  'operationType': 1,
  'vehicleId': '',
  'naptanId': '940GZZDLSOQ',
  'stationName': 'South Quay DLR Station',
  'lineId': 'dlr',
  'lineName': 'DLR',
  'platformName': 'Platform 2',
  'direction': 'inbound',
  'bearing': '',
  'destinationNaptanId': '940GZZDLBNK',
  'destinationName': 'Bank DLR Station',
  'timestamp': '2025-04-08T09:41:20.3911746Z',
  'timeToStation': 588,
  'currentLocation': '',
  'towards': '',
  'expectedArrival': '2025-04-08T09:51:08Z',
  'timeToLive': '2025-04-08T09:51:08Z',
  'modeName': 'dlr',
  'timing': {'$type': 'Tfl.Api.Presentation.Entities.PredictionTiming, Tfl.Api.Presentation.Entities',
   'countdownServerAdjustment': '00:00:00',
   'source': '0001-01-01T00:00:00',
   'insert': '0001-01-01T00:00:00',
   'read': '2025-04-08T09:41:08.296Z',
   'sent': '2025-04-08T09:41:20Z',
   'received': '0001-01-01T00:00:00'}},
 {'$type': 'Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities',
  'id': '-1249460012',
  'operationType': 1,
  'vehicleId': '',
  'naptanId': '940GZZDLSOQ',
  'stationName': 'South Quay DLR Station',
  'lineId': 'dlr',
  'lineName': 'DLR',
  'platformName': 'Platform 1',
  'direction': 'outbound',
  'bearing': '',
  'destinationNaptanId': '940GZZDLLEW',
  'destinationName': 'Lewisham DLR Station',
  'timestamp': '2025-04-08T09:41:20.3911746Z',
  'timeToStation': 107,
  'currentLocation': '',
  'towards': '',
  'expectedArrival': '2025-04-08T09:43:07Z',
  'timeToLive': '2025-04-08T09:43:07Z',
  'modeName': 'dlr',
  'timing': {'$type': 'Tfl.Api.Presentation.Entities.PredictionTiming, Tfl.Api.Presentation.Entities',
   'countdownServerAdjustment': '00:00:00',
   'source': '0001-01-01T00:00:00',
   'insert': '0001-01-01T00:00:00',
   'read': '2025-04-08T09:41:08.296Z',
   'sent': '2025-04-08T09:41:20Z',
   'received': '0001-01-01T00:00:00'}},
 {'$type': 'Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities',
  'id': '-1249460012',
  'operationType': 1,
  'vehicleId': '',
  'naptanId': '940GZZDLSOQ',
  'stationName': 'South Quay DLR Station',
  'lineId': 'dlr',
  'lineName': 'DLR',
  'platformName': 'Platform 1',
  'direction': 'outbound',
  'bearing': '',
  'destinationNaptanId': '940GZZDLLEW',
  'destinationName': 'Lewisham DLR Station',
  'timestamp': '2025-04-08T09:41:20.3911746Z',
  'timeToStation': 467,
  'currentLocation': '',
  'towards': '',
  'expectedArrival': '2025-04-08T09:49:07Z',
  'timeToLive': '2025-04-08T09:49:07Z',
  'modeName': 'dlr',
  'timing': {'$type': 'Tfl.Api.Presentation.Entities.PredictionTiming, Tfl.Api.Presentation.Entities',
   'countdownServerAdjustment': '00:00:00',
   'source': '0001-01-01T00:00:00',
   'insert': '0001-01-01T00:00:00',
   'read': '2025-04-08T09:41:08.296Z',
   'sent': '2025-04-08T09:41:20Z',
   'received': '0001-01-01T00:00:00'}},
 {'$type': 'Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities',
  'id': '-1249460012',
  'operationType': 1,
  'vehicleId': '',
  'naptanId': '940GZZDLSOQ',
  'stationName': 'South Quay DLR Station',
  'lineId': 'dlr',
  'lineName': 'DLR',
  'platformName': 'Platform 1',
  'direction': 'outbound',
  'bearing': '',
  'destinationNaptanId': '940GZZDLLEW',
  'destinationName': 'Lewisham DLR Station',
  'timestamp': '2025-04-08T09:41:20.3911746Z',
  'timeToStation': 767,
  'currentLocation': '',
  'towards': '',
  'expectedArrival': '2025-04-08T09:54:07Z',
  'timeToLive': '2025-04-08T09:54:07Z',
  'modeName': 'dlr',
  'timing': {'$type': 'Tfl.Api.Presentation.Entities.PredictionTiming, Tfl.Api.Presentation.Entities',
   'countdownServerAdjustment': '00:00:00',
   'source': '0001-01-01T00:00:00',
   'insert': '0001-01-01T00:00:00',
   'read': '2025-04-08T09:41:08.296Z',
   'sent': '2025-04-08T09:41:20Z',
   'received': '0001-01-01T00:00:00'}}]

In [39]:
class Timing(BaseModel):
    countdownServerAdjustment: str
    source: dt.datetime
    insert: dt.datetime
    read: dt.datetime

class Arrival(BaseModel):
    type: t.Annotated[str, Field(alias="$type")]
    id: int
    timing: Timing

Arrivals = TypeAdapter(list[Arrival])

In [40]:
data = Arrivals.validate_json(resp.content)
data

[Arrival(type='Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities', id=-1249460012, timing=Timing(countdownServerAdjustment='00:00:00', source=datetime.datetime(1, 1, 1, 0, 0), insert=datetime.datetime(1, 1, 1, 0, 0), read=datetime.datetime(2025, 4, 8, 9, 41, 8, 296000, tzinfo=TzInfo(UTC)))),
 Arrival(type='Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities', id=-1249460012, timing=Timing(countdownServerAdjustment='00:00:00', source=datetime.datetime(1, 1, 1, 0, 0), insert=datetime.datetime(1, 1, 1, 0, 0), read=datetime.datetime(2025, 4, 8, 9, 41, 8, 296000, tzinfo=TzInfo(UTC)))),
 Arrival(type='Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities', id=-1249460012, timing=Timing(countdownServerAdjustment='00:00:00', source=datetime.datetime(1, 1, 1, 0, 0), insert=datetime.datetime(1, 1, 1, 0, 0), read=datetime.datetime(2025, 4, 8, 9, 41, 8, 296000, tzinfo=TzInfo(UTC)))),
 Arrival(type='Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities', id=-1249460012, timing=Timing(countdownServerAdjustment='00:00:00', source=datetime.datetime(1, 1, 1, 0, 0), insert=datetime.datetime(1, 1, 1, 0, 0), read=datetime.datetime(2025, 4, 8, 9, 41, 8, 296000, tzinfo=TzInfo(UTC)))),
 Arrival(type='Tfl.Api.Presentation.Entities.Prediction, Tfl.Api.Presentation.Entities', id=-1249460012, timing=Timing(countdownServerAdjustment='00:00:00', source=datetime.datetime(1, 1, 1, 0, 0), insert=datetime.datetime(1, 1, 1, 0, 0), read=datetime.datetime(2025, 4, 8, 9, 41, 8, 296000, tzinfo=TzInfo(UTC))))]

In [41]:
pl.DataFrame(data)

shape: (5, 3)
┌─────────────────────────────────┬─────────────┬─────────────────────────────────┐
│ type                            ┆ id          ┆ timing                          │
│ ---                             ┆ ---         ┆ ---                             │
│ str                             ┆ i64         ┆ struct[4]                       │
╞═════════════════════════════════╪═════════════╪═════════════════════════════════╡
│ Tfl.Api.Presentation.Entities.… ┆ -1249460012 ┆ {"00:00:00",0001-01-01 00:00:0… │
│ Tfl.Api.Presentation.Entities.… ┆ -1249460012 ┆ {"00:00:00",0001-01-01 00:00:0… │
│ Tfl.Api.Presentation.Entities.… ┆ -1249460012 ┆ {"00:00:00",0001-01-01 00:00:0… │
│ Tfl.Api.Presentation.Entities.… ┆ -1249460012 ┆ {"00:00:00",0001-01-01 00:00:0… │
│ Tfl.Api.Presentation.Entities.… ┆ -1249460012 ┆ {"00:00:00",0001-01-01 00:00:0… │
└─────────────────────────────────┴─────────────┴─────────────────────────────────┘

## 4. Cloud storage, out of core processing with the new streaming engine

Polars can read data in cloud storage natively. Just pass the appropriate `storage_options`:

In [42]:
storage_options = {
    "aws_access_key_id": "minioadmin",
    "aws_secret_access_key": "minioadmin",
    "endpoint_url": "http://127.0.0.1:9032"
}

pl.read_parquet("s3://data/questions-sample.parquet", storage_options=storage_options).head()

shape: (5, 7)
┌──────────┬─────────────┬─────────────────┬────────────┬───────┬─────────────────┬────────────────┐
│ Id       ┆ OwnerUserId ┆ CreationDate    ┆ ClosedDate ┆ Score ┆ Title           ┆ Body           │
│ ---      ┆ ---         ┆ ---             ┆ ---        ┆ ---   ┆ ---             ┆ ---            │
│ i64      ┆ str         ┆ str             ┆ str        ┆ i64   ┆ str             ┆ str            │
╞══════════╪═════════════╪═════════════════╪════════════╪═══════╪═════════════════╪════════════════╡
│ 8869230  ┆ 1109161     ┆ 2012-01-15T11:1 ┆ NA         ┆ 1     ┆ How to display  ┆ <p>I have a    │
│          ┆             ┆ 1:05Z           ┆            ┆       ┆ two or more     ┆ question about │
│          ┆             ┆                 ┆            ┆       ┆ mar…            ┆ the…           │
│ 31915780 ┆ 4021972     ┆ 2015-08-10T09:1 ┆ NA         ┆ -2    ┆ AngularJS:      ┆ <p>when I get  │
│          ┆             ┆ 5:43Z           ┆            ┆       ┆ $http.get 405   ┆ a request from │
│          ┆             ┆                 ┆            ┆       ┆ (Meth…          ┆ a…             │
│ 30964930 ┆ 2786156     ┆ 2015-06-21T13:1 ┆ NA         ┆ 0     ┆ Invariant       ┆ <p>I'm reading │
│          ┆             ┆ 6:50Z           ┆            ┆       ┆ parameters in   ┆ Bloch's        │
│          ┆             ┆                 ┆            ┆       ┆ Java            ┆ Effecti…       │
│ 38084100 ┆ 2938167     ┆ 2016-06-28T18:5 ┆ NA         ┆ 0     ┆ How to make     ┆ <p>For         │
│          ┆             ┆ 1:24Z           ┆            ┆       ┆ Excel macro     ┆ splitting a    │
│          ┆             ┆                 ┆            ┆       ┆ splitt…         ┆ file into s…   │
│ 9601400  ┆ 346977      ┆ 2012-03-07T12:1 ┆ NA         ┆ 2     ┆ Rails Custom    ┆ <p>I'm trying  │
│          ┆             ┆ 9:37Z           ┆            ┆       ┆ Validators:     ┆ to write up a  │
│          ┆             ┆                 ┆            ┆       ┆ Testi…          ┆ ra…            │
└──────────┴─────────────┴─────────────────┴────────────┴───────┴─────────────────┴────────────────┘

Or create an appropriate credential provider:

In [43]:
def get_credentials() -> pl.CredentialProviderFunctionReturn:
    expiry = None

    return {
        "aws_access_key_id": "minioadmin",
        "aws_secret_access_key": "minioadmin",
    }, expiry

In [44]:
pl.read_parquet("s3://data/questions-sample.parquet", credential_provider=get_credentials, storage_options={"endpoint_url": "http://127.0.0.1:9032"}).head()

shape: (5, 7)
┌──────────┬─────────────┬─────────────────┬────────────┬───────┬─────────────────┬────────────────┐
│ Id       ┆ OwnerUserId ┆ CreationDate    ┆ ClosedDate ┆ Score ┆ Title           ┆ Body           │
│ ---      ┆ ---         ┆ ---             ┆ ---        ┆ ---   ┆ ---             ┆ ---            │
│ i64      ┆ str         ┆ str             ┆ str        ┆ i64   ┆ str             ┆ str            │
╞══════════╪═════════════╪═════════════════╪════════════╪═══════╪═════════════════╪════════════════╡
│ 8869230  ┆ 1109161     ┆ 2012-01-15T11:1 ┆ NA         ┆ 1     ┆ How to display  ┆ <p>I have a    │
│          ┆             ┆ 1:05Z           ┆            ┆       ┆ two or more     ┆ question about │
│          ┆             ┆                 ┆            ┆       ┆ mar…            ┆ the…           │
│ 31915780 ┆ 4021972     ┆ 2015-08-10T09:1 ┆ NA         ┆ -2    ┆ AngularJS:      ┆ <p>when I get  │
│          ┆             ┆ 5:43Z           ┆            ┆       ┆ $http.get 405   ┆ a request from │
│          ┆             ┆                 ┆            ┆       ┆ (Meth…          ┆ a…             │
│ 30964930 ┆ 2786156     ┆ 2015-06-21T13:1 ┆ NA         ┆ 0     ┆ Invariant       ┆ <p>I'm reading │
│          ┆             ┆ 6:50Z           ┆            ┆       ┆ parameters in   ┆ Bloch's        │
│          ┆             ┆                 ┆            ┆       ┆ Java            ┆ Effecti…       │
│ 38084100 ┆ 2938167     ┆ 2016-06-28T18:5 ┆ NA         ┆ 0     ┆ How to make     ┆ <p>For         │
│          ┆             ┆ 1:24Z           ┆            ┆       ┆ Excel macro     ┆ splitting a    │
│          ┆             ┆                 ┆            ┆       ┆ splitt…         ┆ file into s…   │
│ 9601400  ┆ 346977      ┆ 2012-03-07T12:1 ┆ NA         ┆ 2     ┆ Rails Custom    ┆ <p>I'm trying  │
│          ┆             ┆ 9:37Z           ┆            ┆       ┆ Validators:     ┆ to write up a  │
│          ┆             ┆                 ┆            ┆       ┆ Testi…          ┆ ra…            │
└──────────┴─────────────┴─────────────────┴────────────┴───────┴─────────────────┴────────────────┘

For out of core processing, you can use the `pl.scan_*` functions, which return a `LazyFrame` instead of a `DataFrame`:

In [45]:
lf = pl.scan_parquet("data/questions-sample.parquet")
lf

You can chain as many operations as you want, they will not be executed:

In [46]:
lf.filter(pl.col("Title").str.starts_with("W"))

To execute the results, you need to call `.collect()`:

In [47]:
(
    pl
    .scan_parquet("s3://data/questions-sample.parquet", storage_options=storage_options)
    .filter(pl.col("Title").str.starts_with("W"))
    .collect()
)

shape: (643, 7)
┌──────────┬─────────────┬────────────────┬────────────────┬───────┬───────────────┬───────────────┐
│ Id       ┆ OwnerUserId ┆ CreationDate   ┆ ClosedDate     ┆ Score ┆ Title         ┆ Body          │
│ ---      ┆ ---         ┆ ---            ┆ ---            ┆ ---   ┆ ---           ┆ ---           │
│ i64      ┆ str         ┆ str            ┆ str            ┆ i64   ┆ str           ┆ str           │
╞══════════╪═════════════╪════════════════╪════════════════╪═══════╪═══════════════╪═══════════════╡
│ 14245370 ┆ 408070      ┆ 2013-01-09T19: ┆ NA             ┆ -1    ┆ Why won't     ┆ <p>I have     │
│          ┆             ┆ 56:15Z         ┆                ┆       ┆ this Ruby     ┆ some simple   │
│          ┆             ┆                ┆                ┆       ┆ script for…   ┆ text pro…     │
│ 17194380 ┆ 2182401     ┆ 2013-06-19T14: ┆ NA             ┆ 0     ┆ Working with  ┆ <p>I need to  │
│          ┆             ┆ 48:40Z         ┆                ┆       ┆ clipboard     ┆ copy some     │
│          ┆             ┆                ┆                ┆       ┆               ┆ text fr…      │
│ 25915600 ┆ 484661      ┆ 2014-09-18T14: ┆ 2014-09-18T14: ┆ 3     ┆ What does     ┆ <p>I ran      │
│          ┆             ┆ 34:31Z         ┆ 42:20Z         ┆       ┆ '+i' mean in  ┆ across this   │
│          ┆             ┆                ┆                ┆       ┆ Java?         ┆ while rev…    │
│ 22782190 ┆ 3484378     ┆ 2014-04-01T09: ┆ NA             ┆ 0     ┆ Why the code  ┆ <p>I have     │
│          ┆             ┆ 46:54Z         ┆                ┆       ┆ goes into     ┆ just started  │
│          ┆             ┆                ┆                ┆       ┆ Infinit…      ┆ with C …      │
│ 34125830 ┆ 264052      ┆ 2015-12-07T03: ┆ NA             ┆ 0     ┆ Why maven     ┆ <p>Every time │
│          ┆             ┆ 12:47Z         ┆                ┆       ┆ prevent me    ┆ I run "Maven  │
│          ┆             ┆                ┆                ┆       ┆ from choo…    ┆ upd…          │
│ …        ┆ …           ┆ …              ┆ …              ┆ …     ┆ …             ┆ …             │
│ 19417340 ┆ 2770892     ┆ 2013-10-17T02: ┆ NA             ┆ 6     ┆ Why are       ┆ <p>Consider   │
│          ┆             ┆ 39:23Z         ┆                ┆       ┆ pA,pB,pC not  ┆ the following │
│          ┆             ┆                ┆                ┆       ┆ equal?        ┆ prog…         │
│ 4341070  ┆ 289024      ┆ 2010-12-02T23: ┆ NA             ┆ 0     ┆ Wordpress     ┆ <p>in this    │
│          ┆             ┆ 27:23Z         ┆                ┆       ┆ post via      ┆ function</p>  │
│          ┆             ┆                ┆                ┆       ┆ XMLRC         ┆               │
│          ┆             ┆                ┆                ┆       ┆               ┆ <p>fu…        │
│ 14015340 ┆ 1925606     ┆ 2012-12-23T22: ┆ NA             ┆ 3     ┆ WebBrowser    ┆ <p>I have a   │
│          ┆             ┆ 51:39Z         ┆                ┆       ┆ OnPropertyCha ┆ webpage, and  │
│          ┆             ┆                ┆                ┆       ┆ nge ev…       ┆ an in…        │
│ 18122100 ┆ 1899840     ┆ 2013-08-08T09: ┆ 2013-08-30T09: ┆ -1    ┆ Why Settings  ┆ <p>I have a   │
│          ┆             ┆ 10:39Z         ┆ 30:17Z         ┆       ┆ app doesnot   ┆ created an    │
│          ┆             ┆                ┆                ┆       ┆ list …        ┆ app, co…      │
│ 29082490 ┆ 4676993     ┆ 2015-03-16T16: ┆ NA             ┆ 0     ┆ Webservice    ┆ <p>I want to  │
│          ┆             ┆ 50:21Z         ┆                ┆       ┆ for bing map  ┆ calculate the │
│          ┆             ┆                ┆                ┆       ┆ to get…       ┆ dis…          │
└──────────┴─────────────┴────────────────┴────────────────┴───────┴───────────────┴───────────────┘